---
- name: Install CakePHP 2.x channel
  become: true
  become_user: root
  command: pear channel-discover pear.cakephp.org

- name: Install CakePHP 2.x binaries
  become: true
  become_user: root
  command: pear install cakephp/CakePHP

- stat: path=/vagrant/webroot
  register: p

- name: Installing Cake Base archive
  become: true
  become_user: root
  unarchive: src=https://raw.githubusercontent.com/cpierce/cakephp-vagrant-setup/master/resources/bases/cake3.zip dest=/vagrant/ copy=no
  when: p.stat.exists == False

- name: Create logs directory
  file: path=/vagrant/logs state=directory mode=0777

- name: Create tmp directory
  file: path=/vagrant/tmp state=directory mode=0777

- name: Create sessions directory
  file: path=/vagrant/tmp/sessions state=directory mode=0777

- name: app link create
  file: src=app.development.php dest=/vagrant/config/app.php state=link force=yes

- name: composer update
  become: true
  become_user: root
  shell: composer update
  args:
    chdir: /vagrant
  tags: composer_update
