---
- name: Update packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    # Basics
    - build-essential
    - zip
    - s3cmd
    - bundler
    - memcached
    - redis-server
    - npm
    - nodejs

    # Database
    - mysql-server
    - mysql-client

    # Web Dev
    - nginx
    - php-cli
    - php-fpm
    - php-gd
    - php-sqlite3
    - php-imap
    - php-mysql
    - php-curl
    - php-json
    - php-xdebug
    - php-redis
    - php-imagick
    - php-memcached
    - php-intl
    - php-mbstring
    - php-pear
    - php-ldap

    # Other tools
    - python3-pymysql
    - phpunit
    - ruby
    - ruby-dev
    - libsqlite3-dev
    - swaks

- name: Autoremove packages
  apt:
    autoremove: yes

- name: Set correct timezone
  copy: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime owner=root group=root mode=0644

- name: Update timezone
  template: src=timezone.j2 dest=/etc/timezone
  notify: update tzdata

- name: Download composer
  get_url: url=https://getcomposer.org/installer dest=/tmp/composer-installer.php mode=0755

- name: Install composer
  become: true
  become_user: root
  shell: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
  tags: composer

- name: PHP fpm log permissions
  file: path=/var/log/php7.4-fpm.log state=touch mode=0644
