---
- name: Start MySQL service
  service: name=mysql state=started

- name: Create my_app user
  community.mysql.mysql_user: 
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: my_app
    host: "%"
    password: secret
    priv: "*.*:ALL,GRANT"
    state: present

- name: Create my_app database
  community.mysql.mysql_db:
    name: my_app
    state: present
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''

- name: Copy MySQL file to server
  template: src=my.cnf.j2 dest=/home/vagrant/.my.cnf owner=vagrant group=vagrant mode=0600
